### ISSUE TITLE
Alert startsAt, Silence createdAt and createdBy

### ISSUE THREAD

**Issue by auhlig** [sapcc/grafana-prometheus-alertmanager-datasource#3]
We should display:
(1) for how long an alert is firing in hours|days|weeks. 
     The `startsAt` field is already present in the alert. Maybe just `date() - startsAt | humanizeTime` 

For the next steps we need the silence referenced by a silenced alert: `status.silencedBy=[ <silenceID> ]`. Find the silence by `GET ../api/v1/silence/<silenceID>`, which returns
```json
{
	"status": "success",
	"data": {
		"id": "<silenceID>",
		"startsAt": "2018-11-16T12:10:33.739066424Z",
		"createdBy": "<creator>",
                 ...
	}
}
```
(2) for how long an alert is silenced
      use `time.Now() - startsAt`

(3) who silenced an alert
      use `createdBy`

**Comment by stefanhipfel** [comment]
https://github.com/sapcc/grafana-prometheus-alertmanager-datasource/commit/80f59d062f0f47af6a9a2ee4495b3402c52222a1
